[package]
name = "nimiq-network-interface"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Nimiq's network implementation in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
bitflags = "1.2"
derive_more = "0.99"
futures = { package = "futures-util", version = "0.3" }
log = { package = "tracing", version = "0.1", features = ["log"] }
multiaddr = "0.18"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.29", features = ["rt"] }
tokio-stream = { version = "0.1", features = ["default", "sync"] }

nimiq-serde = { path = "../serde" }

[dev-dependencies]
nimiq-test-log = { path = "../test-log" }
