[package]
name = "nimiq-mmr"
version = "0.1.0"
authors = ["Pascal Berrang <contact@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
description = "Merkle Mountain Range primitive for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[dependencies]
serde = { version = "1.0", optional = true }

nimiq-serde = { path = "../../serde", optional = true }

[dev-dependencies]
nimiq-test-log = { path = "../../test-log" }

[features]
serde-derive = ["nimiq-serde", "serde"]
